# Generated by Django 3.2.15 on 2022-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thisapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geeksmodel',
            name='again',
            field=models.CharField(default='wekf', max_length=50),
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='oneMore',
            field=models.CharField(default='wekf', max_length=50),
        ),
    ]
